version: '3.8'

services:
  apache:
    image: php:8.1-apache
    container_name: php-apache
    ports:
      - 3000:80
    volumes:
      - ./web:/var/www/html
    networks:
      - default
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.28
    container_name: bbdd
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - default
    # volumes:
    #   - mysql_data:/var/lib/mysql
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
  
  app:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports: 
      - '8080:80'
    environment:
      PMA_HOST: mysql
    networks:
      - default
      
volumes:
    persistent: